# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [26]:
import numpy as np
print(np.zeros((2, 3)))

print(np.empty((2, 3)))
呼叫 zeros()、ones() 函式，可以依照傳入的形狀引數，建立元素全為 0、全為 1 的陣列。
使用 empty() 函式則是不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定。

SyntaxError: invalid syntax (<ipython-input-26-2419b2bc295d>, line 5)

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [27]:
# 記得先 Import 正確的套件

'''
Your Code
'''

'\nYour Code\n'

In [28]:
# 參考解答

a = np.random.rand(2, 3)
print(a)
b = a//1
print(b)

[[0.33107006 0.44073102 0.85832021]
 [0.41631859 0.29654452 0.59171373]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [29]:
m = 20
n = 40

c = abs((a - b)) * (n - m)
ans = c + m
ans

array([[26.62140125, 28.8146204 , 37.16640427],
       [28.32637171, 25.93089044, 31.83427466]])